package urls

//Define route paths to be used in routers package
const STATIC_PATH string = "/static/"
const ROOT_PATH string = "/"
const LOGOUT_PATH string = "/logout"
const NOT_FOUND_PATH string = "/404"
const AUTH_PATH string = "/auth/{provider}"
const AUTH_CALLBACK_PATH string = "/auth/{provider}/callback"
const PROFILE_PATH string = "/profile/"
const HOME_PATH string = PROFILE_PATH + "home/"
const PROFILE_VIEW_PATH string = PROFILE_PATH + "view/{userid}/"
const PROFILE_EDIT_PATH string = PROFILE_PATH + "edit/"
const BC_PATH = "/bc/"
const PAY_SLIP_PATH string = BC_PATH + "payslip/"
const USERS_PATH string = BC_PATH + "users/"
const METRICS_PATH string = BC_PATH + "metrics/"
const PROJECT_SHOWCASE_VIEW_PATH = BC_PATH + "showcase/"
const ADMIN_PATH string = "/admin/"
const ADMIN_METRICS_OPS_ADD_PATH string = ADMIN_PATH + "metrics/ops/add/"
