package templates

// Template Variables
const NOTFOUND string = "templates/404.html"
const LOGIN string = "templates/login.html"
const BASE string = "templates/base.html"
const NOTIFICATIONS string = "templates/notifications.html"
const TICKER string = "templates/ticker.html"
const HOME string = "templates/home.html"
const WALL_POST string = "templates/wall_post.html"
const PROFILE_VIEW string = "templates/view_profile.html"
const PROFILE_EDIT string = "templates/edit_profile.html"
const USERS string = "templates/users.html"
const METRICS string = "templates/metrics.html"
const METRICS_OPS_ADD string = "templates/metrics_ops_add.html"
const DAILY_LOGS string = "templates/daily_logs.html"
const DAILY_LOGS_ADD string = "templates/daily_logs_add.html"
const DAILY_LOGS_VIEW string = "templates/daily_logs_view.html"
const POST_ADD string = "templates/post_add.html"
const ANNOUNCEMENTS string = "templates/announcements.html"
const ABOUT string = "templates/about.html"
const PROJECT_VIEW string = "templates/project_view.html"
const PROJECT_EDIT string = "templates/project_edit.html"
const PROJECTS string = "templates/projects.html"
const PROJECT_ADD string = "templates/project_add.html"
const RECRUITMENT string = "templates/recruitment.html"
const CANDIDATE_ADD string = "templates/candidate_add.html"
const CANDIDATE_VIEW string = "templates/candidate_view.html"
const CANDIDATE_EDIT string = "templates/candidate_edit.html"
const PAYSLIP string = "templates/payslip.html"
const PAYSLIP_HISTORY string = "templates/payslip_history.html"
const APPROVALS string = "templates/approvals.html"
const APPROVALS_PAYSLIP string = "templates/approvals_payslips.html"
